# Generated by Django 4.0.2 on 2022-03-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_association_customuser_bio_customuser_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
    ]
