# Generated by Django 4.0.2 on 2022-03-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_categories_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
