# Generated by Django 4.0.2 on 2022-03-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_comments_created_at_comments_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='author',
        ),
    ]
