# Generated by Django 4.0.2 on 2022-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_owner_association_project_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='association_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
