# Generated by Django 4.0.2 on 2022-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_association_association_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='association_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
