# Generated by Django 4.0.2 on 2022-04-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_association_association_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='forest_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
